@BaseUrl=https://localhost:7044

###
POST {{BaseUrl}}/CheckingAccount
Content-Type: application/json  

{
  "OpeningBalance": 10000
}
 
###
@CheckingAccountId=db3a8f55-726c-4552-a762-7057a112ead0

###
GET {{BaseUrl}}/CheckingAccount/{{CheckingAccountId}}/balance
Content-Type: application/json   

###
POST {{BaseUrl}}/CheckingAccount/{{CheckingAccountId}}/debit
Content-Type: application/json 

{
  "Amount": 1000
}
###
POST {{BaseUrl}}/CheckingAccount/{{CheckingAccountId}}/credit
Content-Type: application/json 

{
  "Amount": 500
}

###
POST {{BaseUrl}}/Atm 
Content-Type: application/json   

{
  "Amount": 10000
}

###
POST {{BaseUrl}}/Atm/51c586fc-baa2-4567-a7f1-bcfede89e9ab/withdraw
Content-Type: application/json   

{
  "CheckingAccountId":"{{CheckingAccountId}}",
  "Amount": 1000
}

###
POST {{BaseUrl}}/CheckingAccount/{{CheckingAccountId}}/recurringPayment
Content-Type: application/json   

{
  "PaymentId":"61c586fc-baa2-4567-a7f1-bcfede89e9ac",
  "PaymentAmount": 1,
  "PaymentRecurrsEveryMinutes":1
}
